# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nac', models.DateField()),
                ('escolaridad', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
